### ISSUE TITLE
What exactly are the secrets

### ISSUE THREAD

**Issue by PBahner** [Sajantoor/Notion-GitHub-Issues-Automation#2]
If I understood right "NOTION_API_KEY" is the cookie "token_v2"? Or am I wrong and have to create a integration and use its secret?

Do I have to put the whole url for the notion database id or only the long string from the url?
And how do I get the NOTION_PAGE_ID?

I would be very grateful if you could help me. Thanks!

**Comment by Sajantoor** [comment]
Hi,

Sorry I've been meaning to update the documentation but haven't gotten a chance to. 

`NOTION_API_KEY`: Is the "integration token" more information on it is here: https://developers.notion.com/docs#create-a-new-integration

`NOTION_DATABASE_ID`: Isn't the full string just the part that's detailed in the Notion API documentation. 
![image](https://user-images.githubusercontent.com/25991050/121099465-bc286b80-c7ac-11eb-922e-c637afa9ba0b.png)


`NOTION_PAGE_ID`: Is the in the URL that contains your database. For example it would be: `https://www.notion.so/[page-name]-[page-id].`

Sorry the documentation for this part isn't great, I'll update that as soon as possible. Let me know if you have any more questions!
