### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url: ...

### ISSUE THREAD

**Issue by PBahner** [Sajantoor/Notion-GitHub-Issues-Automation#3]
I used the secrets as explained in #2 . I also set the permission "Can edit" for my integration on the page that includes the database.

![image](https://user-images.githubusercontent.com/49592255/121244687-76000480-c89f-11eb-8229-c9191f2001d4.png)

But Unfortunately I get this error: 

![image](https://user-images.githubusercontent.com/49592255/121244465-2f120f00-c89f-11eb-8a3a-dc0fef7e8eb4.png)

seems like the authorization doesn't work...
Thanks if you could fix that / help me :)

**Comment by Sajantoor** [comment]
How are you setting it up? This is a python error.

**Comment by Sajantoor** [comment]
I've updated the readme for this project, I hope that helps :)
